services:
  NetWatchTelnetAttackPod:
    build: .
    image: docker.netwatch.team/netwatch_telnet-attackpod:1.0
    container_name: netwatch_telnet-attackpod
    environment:
      SENSOR_UUID: "your-unique-uuid-here"
      SENSOR_TLP: "CLEAR"
      NETWATCH_COLLECTOR_AUTHORIZATION: ${NETWATCH_COLLECTOR_AUTHORIZATION}
      NETWATCH_COLLECTOR_URL: "https://api.netwatch.team"
      ATTACK_POD_IP: "" # Leave empty for auto-detection
      NETWATCH_TEST_MODE: "false"
    restart: unless-stopped
    ports:
      - "23:2323"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "2"
